### ISSUE TITLE
would the 1.19.4 resource pack work on 1.19.2?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Andre601/Presence-Footsteps-x-Origin-Realms#1]
A few mods and resource packs made for origin realms majorly support 1.19.2 so I was wondering would the 1.19.4 version work well on the 1.19.2 version? And if not would you be able to support it?

**Comment by Andre601** [comment]
The resource pack itself doesn't really provide anything towards Minecraft itself, so you can safely lower the pack version in the `pack.mcmeta` to one that supports your version (Don't ask me which one tho. I don't keep track of those).
